import Contact from "./Contact";
import Education from "./Education";
import HeroSection from "./HeroSection";
import Overview from "./Overview";
import Skills from "./Skills";
import Timeline from "./Timeline";
import WorkHistory from "./WorkHistory";
import Portfolio from "./Portfolio";
import Heads from "./Heads";
import PortfolioMedia from "./PortfolioMedia";
export { Contact, Education, Overview, Skills, Timeline, WorkHistory, HeroSection, Portfolio, PortfolioMedia, Heads };
